/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/particles-tests-3-7765368dcd4f43d4a2c0e3ea42d020d2
title: Particles Tests - 3
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ scale }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene.gltf");
  const { actions } = useAnimations(animations, group);
  // useEffect(() => {
  //   return actions.animation_0.play();
  // });

  return (
    <group ref={group} scale={0.4} dispose={null} position={[1, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_0.geometry}
            material={nodes.mesh_0.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_1.geometry}
            material={nodes.mesh_1.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_2.geometry}
            material={nodes.mesh_2.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_3.geometry}
            material={nodes.mesh_3.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_4.geometry}
            material={nodes.mesh_4.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_5.geometry}
            material={nodes.mesh_5.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_6.geometry}
            material={nodes.mesh_6.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_7.geometry}
            material={nodes.mesh_7.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_8.geometry}
            material={nodes.mesh_8.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_9.geometry}
            material={nodes.mesh_9.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_10.geometry}
            material={nodes.mesh_10.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_11.geometry}
            material={nodes.mesh_11.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_12.geometry}
            material={nodes.mesh_12.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_13.geometry}
            material={nodes.mesh_13.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_14.geometry}
            material={nodes.mesh_14.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_15.geometry}
            material={nodes.mesh_15.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_16.geometry}
            material={nodes.mesh_16.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_17.geometry}
            material={nodes.mesh_17.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_18.geometry}
            material={nodes.mesh_18.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_19.geometry}
            material={nodes.mesh_19.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_20.geometry}
            material={nodes.mesh_20.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_21.geometry}
            material={nodes.mesh_21.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_22.geometry}
            material={nodes.mesh_22.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_23.geometry}
            material={nodes.mesh_23.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_24.geometry}
            material={nodes.mesh_24.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_25.geometry}
            material={nodes.mesh_25.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_26.geometry}
            material={nodes.mesh_26.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_27.geometry}
            material={nodes.mesh_27.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_28.geometry}
            material={nodes.mesh_28.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_29.geometry}
            material={nodes.mesh_29.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_30.geometry}
            material={nodes.mesh_30.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_31.geometry}
            material={nodes.mesh_31.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_32.geometry}
            material={nodes.mesh_32.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_33.geometry}
            material={nodes.mesh_33.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_34.geometry}
            material={nodes.mesh_34.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_35.geometry}
            material={nodes.mesh_35.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_36.geometry}
            material={nodes.mesh_36.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_37.geometry}
            material={nodes.mesh_37.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_38.geometry}
            material={nodes.mesh_38.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_39.geometry}
            material={nodes.mesh_39.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_40.geometry}
            material={nodes.mesh_40.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_41.geometry}
            material={nodes.mesh_41.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_42.geometry}
            material={nodes.mesh_42.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_43.geometry}
            material={nodes.mesh_43.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_44.geometry}
            material={nodes.mesh_44.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_45.geometry}
            material={nodes.mesh_45.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_46.geometry}
            material={nodes.mesh_46.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_47.geometry}
            material={nodes.mesh_47.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_48.geometry}
            material={nodes.mesh_48.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_49.geometry}
            material={nodes.mesh_49.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_50.geometry}
            material={nodes.mesh_50.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_51.geometry}
            material={nodes.mesh_51.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_52.geometry}
            material={nodes.mesh_52.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_53.geometry}
            material={nodes.mesh_53.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_54.geometry}
            material={nodes.mesh_54.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_55.geometry}
            material={nodes.mesh_55.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_56.geometry}
            material={nodes.mesh_56.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_57.geometry}
            material={nodes.mesh_57.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_58.geometry}
            material={nodes.mesh_58.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_59.geometry}
            material={nodes.mesh_59.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_60.geometry}
            material={nodes.mesh_60.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_61.geometry}
            material={nodes.mesh_61.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_62.geometry}
            material={nodes.mesh_62.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_63.geometry}
            material={nodes.mesh_63.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_64.geometry}
            material={nodes.mesh_64.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_65.geometry}
            material={nodes.mesh_65.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_66.geometry}
            material={nodes.mesh_66.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_67.geometry}
            material={nodes.mesh_67.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_68.geometry}
            material={nodes.mesh_68.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_69.geometry}
            material={nodes.mesh_69.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_70.geometry}
            material={nodes.mesh_70.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_71.geometry}
            material={nodes.mesh_71.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_72.geometry}
            material={nodes.mesh_72.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_73.geometry}
            material={nodes.mesh_73.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_74.geometry}
            material={nodes.mesh_74.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_75.geometry}
            material={nodes.mesh_75.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_76.geometry}
            material={nodes.mesh_76.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_77.geometry}
            material={nodes.mesh_77.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_78.geometry}
            material={nodes.mesh_78.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_79.geometry}
            material={nodes.mesh_79.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_80.geometry}
            material={nodes.mesh_80.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_81.geometry}
            material={nodes.mesh_81.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_82.geometry}
            material={nodes.mesh_82.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_83.geometry}
            material={nodes.mesh_83.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_84.geometry}
            material={nodes.mesh_84.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_85.geometry}
            material={nodes.mesh_85.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_86.geometry}
            material={nodes.mesh_86.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_87.geometry}
            material={nodes.mesh_87.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_88.geometry}
            material={nodes.mesh_88.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_89.geometry}
            material={nodes.mesh_89.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_90.geometry}
            material={nodes.mesh_90.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_91.geometry}
            material={nodes.mesh_91.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_92.geometry}
            material={nodes.mesh_92.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_93.geometry}
            material={nodes.mesh_93.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_94.geometry}
            material={nodes.mesh_94.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_95.geometry}
            material={nodes.mesh_95.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_96.geometry}
            material={nodes.mesh_96.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_97.geometry}
            material={nodes.mesh_97.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_98.geometry}
            material={nodes.mesh_98.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_99.geometry}
            material={nodes.mesh_99.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_100.geometry}
            material={nodes.mesh_100.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_101.geometry}
            material={nodes.mesh_101.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_102.geometry}
            material={nodes.mesh_102.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_103.geometry}
            material={nodes.mesh_103.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_104.geometry}
            material={nodes.mesh_104.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_105.geometry}
            material={nodes.mesh_105.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_106.geometry}
            material={nodes.mesh_106.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_107.geometry}
            material={nodes.mesh_107.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_108.geometry}
            material={nodes.mesh_108.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_109.geometry}
            material={nodes.mesh_109.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_110.geometry}
            material={nodes.mesh_110.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_111.geometry}
            material={nodes.mesh_111.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_112.geometry}
            material={nodes.mesh_112.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_113.geometry}
            material={nodes.mesh_113.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_114.geometry}
            material={nodes.mesh_114.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_115.geometry}
            material={nodes.mesh_115.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_116.geometry}
            material={nodes.mesh_116.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_117.geometry}
            material={nodes.mesh_117.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_118.geometry}
            material={nodes.mesh_118.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_119.geometry}
            material={nodes.mesh_119.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_120.geometry}
            material={nodes.mesh_120.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_121.geometry}
            material={nodes.mesh_121.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_122.geometry}
            material={nodes.mesh_122.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_123.geometry}
            material={nodes.mesh_123.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_124.geometry}
            material={nodes.mesh_124.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_125.geometry}
            material={nodes.mesh_125.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_126.geometry}
            material={nodes.mesh_126.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_127.geometry}
            material={nodes.mesh_127.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_128.geometry}
            material={nodes.mesh_128.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_129.geometry}
            material={nodes.mesh_129.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_130.geometry}
            material={nodes.mesh_130.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_131.geometry}
            material={nodes.mesh_131.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_132.geometry}
            material={nodes.mesh_132.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_133.geometry}
            material={nodes.mesh_133.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_134.geometry}
            material={nodes.mesh_134.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_135.geometry}
            material={nodes.mesh_135.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_136.geometry}
            material={nodes.mesh_136.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_137.geometry}
            material={nodes.mesh_137.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_138.geometry}
            material={nodes.mesh_138.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_139.geometry}
            material={nodes.mesh_139.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_140.geometry}
            material={nodes.mesh_140.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_141.geometry}
            material={nodes.mesh_141.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_142.geometry}
            material={nodes.mesh_142.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_143.geometry}
            material={nodes.mesh_143.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_144.geometry}
            material={nodes.mesh_144.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_145.geometry}
            material={nodes.mesh_145.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_146.geometry}
            material={nodes.mesh_146.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_147.geometry}
            material={nodes.mesh_147.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_148.geometry}
            material={nodes.mesh_148.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_149.geometry}
            material={nodes.mesh_149.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_150.geometry}
            material={nodes.mesh_150.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_151.geometry}
            material={nodes.mesh_151.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_152.geometry}
            material={nodes.mesh_152.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_153.geometry}
            material={nodes.mesh_153.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_154.geometry}
            material={nodes.mesh_154.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_155.geometry}
            material={nodes.mesh_155.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_156.geometry}
            material={nodes.mesh_156.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_157.geometry}
            material={nodes.mesh_157.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_158.geometry}
            material={nodes.mesh_158.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_159.geometry}
            material={nodes.mesh_159.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_160.geometry}
            material={nodes.mesh_160.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_161.geometry}
            material={nodes.mesh_161.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_162.geometry}
            material={nodes.mesh_162.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_163.geometry}
            material={nodes.mesh_163.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_164.geometry}
            material={nodes.mesh_164.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_165.geometry}
            material={nodes.mesh_165.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_166.geometry}
            material={nodes.mesh_166.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_167.geometry}
            material={nodes.mesh_167.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_168.geometry}
            material={nodes.mesh_168.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_169.geometry}
            material={nodes.mesh_169.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_170.geometry}
            material={nodes.mesh_170.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_171.geometry}
            material={nodes.mesh_171.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_172.geometry}
            material={nodes.mesh_172.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_173.geometry}
            material={nodes.mesh_173.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_174.geometry}
            material={nodes.mesh_174.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_175.geometry}
            material={nodes.mesh_175.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_176.geometry}
            material={nodes.mesh_176.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_177.geometry}
            material={nodes.mesh_177.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_178.geometry}
            material={nodes.mesh_178.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_179.geometry}
            material={nodes.mesh_179.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_180.geometry}
            material={nodes.mesh_180.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_181.geometry}
            material={nodes.mesh_181.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_182.geometry}
            material={nodes.mesh_182.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_183.geometry}
            material={nodes.mesh_183.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_184.geometry}
            material={nodes.mesh_184.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_185.geometry}
            material={nodes.mesh_185.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_186.geometry}
            material={nodes.mesh_186.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_187.geometry}
            material={nodes.mesh_187.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_188.geometry}
            material={nodes.mesh_188.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_189.geometry}
            material={nodes.mesh_189.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_190.geometry}
            material={nodes.mesh_190.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_191.geometry}
            material={nodes.mesh_191.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_192.geometry}
            material={nodes.mesh_192.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_193.geometry}
            material={nodes.mesh_193.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_194.geometry}
            material={nodes.mesh_194.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_195.geometry}
            material={nodes.mesh_195.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_196.geometry}
            material={nodes.mesh_196.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_197.geometry}
            material={nodes.mesh_197.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_198.geometry}
            material={nodes.mesh_198.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_199.geometry}
            material={nodes.mesh_199.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_200.geometry}
            material={nodes.mesh_200.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_201.geometry}
            material={nodes.mesh_201.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_202.geometry}
            material={nodes.mesh_202.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_203.geometry}
            material={nodes.mesh_203.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_204.geometry}
            material={nodes.mesh_204.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_205.geometry}
            material={nodes.mesh_205.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_206.geometry}
            material={nodes.mesh_206.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_207.geometry}
            material={nodes.mesh_207.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_208.geometry}
            material={nodes.mesh_208.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_209.geometry}
            material={nodes.mesh_209.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_210.geometry}
            material={nodes.mesh_210.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_211.geometry}
            material={nodes.mesh_211.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_212.geometry}
            material={nodes.mesh_212.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_213.geometry}
            material={nodes.mesh_213.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_214.geometry}
            material={nodes.mesh_214.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_215.geometry}
            material={nodes.mesh_215.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_216.geometry}
            material={nodes.mesh_216.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_217.geometry}
            material={nodes.mesh_217.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_218.geometry}
            material={nodes.mesh_218.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_219.geometry}
            material={nodes.mesh_219.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_220.geometry}
            material={nodes.mesh_220.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_221.geometry}
            material={nodes.mesh_221.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_222.geometry}
            material={nodes.mesh_222.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_223.geometry}
            material={nodes.mesh_223.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_224.geometry}
            material={nodes.mesh_224.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_225.geometry}
            material={nodes.mesh_225.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_226.geometry}
            material={nodes.mesh_226.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_227.geometry}
            material={nodes.mesh_227.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_228.geometry}
            material={nodes.mesh_228.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_229.geometry}
            material={nodes.mesh_229.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_230.geometry}
            material={nodes.mesh_230.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_231.geometry}
            material={nodes.mesh_231.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_232.geometry}
            material={nodes.mesh_232.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_233.geometry}
            material={nodes.mesh_233.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_234.geometry}
            material={nodes.mesh_234.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_235.geometry}
            material={nodes.mesh_235.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_236.geometry}
            material={nodes.mesh_236.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_237.geometry}
            material={nodes.mesh_237.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_238.geometry}
            material={nodes.mesh_238.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_239.geometry}
            material={nodes.mesh_239.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_240.geometry}
            material={nodes.mesh_240.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_241.geometry}
            material={nodes.mesh_241.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_242.geometry}
            material={nodes.mesh_242.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_243.geometry}
            material={nodes.mesh_243.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_244.geometry}
            material={nodes.mesh_244.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_245.geometry}
            material={nodes.mesh_245.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_246.geometry}
            material={nodes.mesh_246.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_247.geometry}
            material={nodes.mesh_247.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_248.geometry}
            material={nodes.mesh_248.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_249.geometry}
            material={nodes.mesh_249.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_250.geometry}
            material={nodes.mesh_250.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_251.geometry}
            material={nodes.mesh_251.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_252.geometry}
            material={nodes.mesh_252.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_253.geometry}
            material={nodes.mesh_253.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_254.geometry}
            material={nodes.mesh_254.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_255.geometry}
            material={nodes.mesh_255.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_256.geometry}
            material={nodes.mesh_256.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_257.geometry}
            material={nodes.mesh_257.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_258.geometry}
            material={nodes.mesh_258.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_259.geometry}
            material={nodes.mesh_259.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_260.geometry}
            material={nodes.mesh_260.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_261.geometry}
            material={nodes.mesh_261.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_262.geometry}
            material={nodes.mesh_262.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_263.geometry}
            material={nodes.mesh_263.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_264.geometry}
            material={nodes.mesh_264.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_265.geometry}
            material={nodes.mesh_265.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_266.geometry}
            material={nodes.mesh_266.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_267.geometry}
            material={nodes.mesh_267.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_268.geometry}
            material={nodes.mesh_268.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_269.geometry}
            material={nodes.mesh_269.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_270.geometry}
            material={nodes.mesh_270.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_271.geometry}
            material={nodes.mesh_271.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_272.geometry}
            material={nodes.mesh_272.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_273.geometry}
            material={nodes.mesh_273.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_274.geometry}
            material={nodes.mesh_274.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_275.geometry}
            material={nodes.mesh_275.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_276.geometry}
            material={nodes.mesh_276.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_277.geometry}
            material={nodes.mesh_277.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_278.geometry}
            material={nodes.mesh_278.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_279.geometry}
            material={nodes.mesh_279.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_280.geometry}
            material={nodes.mesh_280.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_281.geometry}
            material={nodes.mesh_281.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_282.geometry}
            material={nodes.mesh_282.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_283.geometry}
            material={nodes.mesh_283.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_284.geometry}
            material={nodes.mesh_284.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_285.geometry}
            material={nodes.mesh_285.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_286.geometry}
            material={nodes.mesh_286.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_287.geometry}
            material={nodes.mesh_287.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_288.geometry}
            material={nodes.mesh_288.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_289.geometry}
            material={nodes.mesh_289.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_290.geometry}
            material={nodes.mesh_290.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_291.geometry}
            material={nodes.mesh_291.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_292.geometry}
            material={nodes.mesh_292.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_293.geometry}
            material={nodes.mesh_293.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_294.geometry}
            material={nodes.mesh_294.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_295.geometry}
            material={nodes.mesh_295.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_296.geometry}
            material={nodes.mesh_296.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_297.geometry}
            material={nodes.mesh_297.material}
          />
        </group>
        <group scale={0}>
          <mesh
            geometry={nodes.mesh_298.geometry}
            material={nodes.mesh_298.material}
          />
        </group>
        <mesh
          geometry={nodes.mesh_299.geometry}
          material={nodes.mesh_299.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
